---
- hosts: "{{ tower_hosts }}"
  gather_facts: yes

  vars:
     tower_hosts: all

  

- name: ADD NEW USER
  user:
    name: "{{ linux_new_user }}"
    shell: /bin/bash
    groups: admin,developers
    append: yes
    
